name: Format Support
description: Request support for an NGDP/CASC format version or feature
title: "[Format]: "
labels: ["enhancement", "format-support"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of NGDP/CASC is affected?
      options:
        - CASC storage
        - NGDP protocol
        - CDN download
        - Encoding
        - Install manifest
        - Download manifest
        - Root file
        - Configuration
        - Other
    validations:
      required: true

  - type: input
    id: wow-version
    attributes:
      label: WoW Version
      description: Which WoW version or build number is this for?
      placeholder: "e.g., 3.3.5a (12340), 9.2.7, Classic Era"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the format or feature that needs support
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to documentation, specifications, or related projects
      placeholder: |
        - WoWDev wiki links
        - Other implementations
        - Specification documents
    validations:
      required: false

  - type: textarea
    id: sample-data
    attributes:
      label: Sample Data
      description: Any sample files, hex dumps, or data structures
      render: text
    validations:
      required: false
